version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "5000:5000"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
