name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /opt/Jeewaka-Medical-Platform
            git fetch origin main
            git reset --hard origin/main

            # Rebuild and restart Docker (uses existing .env)
            docker-compose -f docker-compose.micro.yml --env-file /opt/Jeewaka-Medical-Platform/.env.production down
            docker-compose -f docker-compose.micro.yml --env-file /opt/Jeewaka-Medical-Platform/.env.production up -d --build
